config/routes.rb
Rails.application.routes.draw do
  resources :batches, only: [:index, :new, :create, :show] do
    member do
      get 'output'
      get 'view_params'
      get 'progress'
    end
  end
  resources :configurations

  root to: redirect('/batches')
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :canvas_configuration
  serialize :params, Hash
  serialize :output, Hash

  before_create do
    self.state ||= 'queued'
    self.progress ||= 0
  end

  before_save do
    self.progress = 100 if self.state == 'completed'
  end

  def retry
    self.state = 'queued'
    self.output = {}
    save!
    Seeder::Seeder.new(self).delay.process!
  end
end

app/models/canvas_configuration.rb
class CanvasConfiguration < ActiveRecord::Base
  has_many :batches, dependent: :destroy
  validates_presence_of :name, :domain, :access_token

  def name_with_domain
    "#{name} - #{domain}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController

  before_action only: [:show, :view_params, :output, :progress] do
    @batch = Batch.find params[:id]
  end

  def index
    @batches = Batch.all.includes(:canvas_configuration).order(created_at: :desc)
  end

  def view_params
    render json: @batch.params, status: :ok
  end

  def output
    render json: @batch.output, status: :ok
  end

  def progress
    render json: { progress: @batch.progress || 0 }, status: :ok
  end

  def new
    @batch = Batch.new
    @canvas_configurations = CanvasConfiguration.all
  end

  def create
    @batch = Batch.new batch_params
    if @batch.save
      Seeder::Seeder.new(@batch).delay.process!
      redirect_to batch_path(@batch)
    else
      render 'new'
    end
  end

  private
  def batch_params
    params[:batch][:params][:number_of_courses] = (params[:batch][:params].delete(:number_of_courses_min).to_i..params[:batch][:params].delete(:number_of_courses_max).to_i)
    params[:batch][:params][:number_of_sections] = (params[:batch][:params].delete(:number_of_sections_min).to_i..params[:batch][:params].delete(:number_of_sections_max).to_i)
    params[:batch][:params][:number_of_teachers] = (params[:batch][:params].delete(:number_of_teachers_min).to_i..params[:batch][:params].delete(:number_of_teachers_max).to_i)
    params[:batch][:params][:number_of_students] = (params[:batch][:params].delete(:number_of_students_min).to_i..params[:batch][:params].delete(:number_of_students_max).to_i)
    params[:batch][:params][:number_of_assignments] = (params[:batch][:params].delete(:number_of_assignments_min).to_i..params[:batch][:params].delete(:number_of_assignments_max).to_i)
    params[:batch][:params][:points_possible] = (params[:batch][:params].delete(:points_possible_min).to_i..params[:batch][:params].delete(:points_possible_max).to_i)
    params.require(:batch).permit!
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController

  before_action only: [:destroy, :show, :edit, :update] do
    @configuration = CanvasConfiguration.find params[:id]
  end

  def index
    @configurations = CanvasConfiguration.all
  end

  def new
    @configuration ||= CanvasConfiguration.new
  end

  def create
    @configuration ||= CanvasConfiguration.new configuration_params
    if @configuration.save
      redirect_to configurations_path
    else
      render 'new'
    end
  end

  def update
    if @configuration.update configuration_params
      redirect_to configurations_path
    else
      render 'edit'
    end
  end

  def destroy
    @configuration.destroy
    redirect_to configurations_path
  end

  private
  def configuration_params
    params.require(:canvas_configuration).permit(:name, :domain, :access_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/batches/index.html.erb
<div class="row">
  <div class="col-md-6"><b>Description</b></div>
  <div class="col-md-3"><b>Config name</b></div>
  <div class="col-md-1"><b>State</b></div>
  <div class="col-md-2"><b>Created at</b></div>
</div>
<% @batches.each do |batch| %>
  <div class="row">
    <div class="col-md-6">
      <%= link_to (batch.description.blank? ? batch.created_at : batch.description), batch_path(batch) %>
    </div>
    <div class="col-md-3">
      <%= batch.canvas_configuration.name %>
    </div>
    <div class="col-md-1">
      <%= batch.state %>
    </div>
    <div class="col-md-2">
      <%= batch.created_at %>
    </div>
  </div>
<% end %>

<%= link_to 'New Batch', new_batch_path, class: 'btn btn-primary' %>

app/views/batches/new.html.erb
<h1>New Batch</h1>
<%= bootstrap_form_for @batch, html: { 'data-fv-framework' => 'bootstrap', 'data-fv-icon-valid' => 'glyphicon glyphicon-ok', 'data-fv-icon-invalid' => 'glyphicon glyphicon-remove', 'data-fv-icon-validating' => 'glyphicon glyphicon-refresh' } do |f| %>
  <%= f.select :canvas_configuration_id, options_from_collection_for_select(@canvas_configurations, 'id', 'name_with_domain') %>
  <%= f.text_field :description %>
  <%= f.fields_for :params do |fp| %>
    <div class="row">
      <div class="col-md-6">
        <%= fp.text_field :account_id, value: 'self', label: 'Canvas Account Id', 'data-fv-notempty' => 'true' %>
      </div>
      <div class="col-md-6">
        <%= fp.text_field :term_id, label: 'Canvas Term Id (optional)' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :number_of_courses_min, value: 1, min: 1, max: 1000, label: 'Minimum Number of Courses' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :number_of_courses_max, value: 1, min: 1, max: 1000, label: 'Maximum Number of Courses' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :number_of_sections_min, value: 1, min: 1, max: 1000, label: 'Minimum Number of Sections' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :number_of_sections_max, value: 1, min: 1, max: 1000, label: 'Maximum Number of Sections' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :number_of_teachers_min, value: 1, min: 1, max: 1000, label: 'Minimum Number of Teachers' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :number_of_teachers_max, value: 2, min: 1, max: 1000, label: 'Maximum Number of Teachers' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :number_of_students_min, value: 5, min: 1, max: 1000, label: 'Minimum Number of Students' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :number_of_students_max, value: 20, min: 1, max: 1000, label: 'Maximum Number of Students' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :number_of_assignments_min, value: 5, min: 1, max: 1000, label: 'Minimum Number of Assignments' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :number_of_assignments_max, value: 20, min: 1, max: 1000, label: 'Maximum Number of Assignments' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :points_possible_min, value: 5, min: 1, max: 1000, label: 'Minimum Points Possible' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :points_possible_max, value: 10, min: 1, max: 1000, label: 'Maximum Points Possible' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= fp.number_field :students_with_submissions, value: 80, min: 0, max: 100, label: '% of Students With Submissions' %>
      </div>
      <div class="col-md-6">
        <%= fp.number_field :grade_submissions, value: 80, min: 0, max: 100, label: '% of Submissions to be Graded' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="control-label">Submission Types</label>
          <% Seeder::Models::Assignment::TYPES_OF_ASSIGNMENTS.each do |type| %>
            <div class="checkbox" style="margin-left: 20px;">
              <input type="checkbox" name="batch[params][types_of_assignments][]" value="<%= type %>" checked="checked">
              <%= type.to_s.titleize %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= f.form_group do %>
    <%= f.primary %>
  <% end %>
<% end %>

app/views/batches/show.html.erb
<ul>
  <li><b>Description: </b><%= @batch.description %></li>
  <li><b>State: </b><%= @batch.state %></li>
  <li><b>Configuration Name: </b><%= @batch.canvas_configuration.name %></li>
  <li><b>Domain: </b><%= link_to @batch.canvas_configuration.domain, @batch.canvas_configuration.domain %></li>
  <li><b>Created at: </b><%= @batch.created_at %></li>
  <% if @batch.state == 'completed' %>
    <li><%= link_to 'Go to first course', "#{@batch.canvas_configuration.domain}/courses/#{@batch.output[:courses].first['id']}", target: '_blank' %></li>
  <% end %>
</ul>
<% if @batch.state == 'running' || @batch.state == 'queued' %>
  <div class="row">
    <div class="col-md-12">
      <div class="progress">
        <div class="progress-bar progress-bar-striped active" style="min-width: 2em; width: <%= @batch.progress %>%">
          <%= @batch.progress %>%
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <label class="control-label">Batch Params</label>
    <%= link_to '[View in new tab]', view_params_batch_path(@batch), target: '_blank' %>
    <pre><%= JSON.pretty_generate(@batch.params.as_json) %></pre>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <label class="control-label">Results</label>
    <%= link_to '[View in new tab]', output_batch_path(@batch), target: '_blank' %>
    <pre><%= JSON.pretty_generate(@batch.output.as_json) %></pre>
  </div>
</div>

app/views/configurations/_form.html.erb
<%= bootstrap_form_for @configuration, url: (@configuration.new_record? ? configurations_path : configuration_path(@configuration)), layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-6' do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :domain %>
  <%= f.text_field :access_token %>
  <div class="col-md-offset-2 col-md-2">
    <div style="margin-left: -10px;"><%= f.primary %></div>
  </div>
<% end %>

app/views/configurations/edit.html.erb
<%= render partial: 'form' %>

app/views/configurations/index.html.erb
<div class="row">
  <div class="col-md-6"><b>Name</b></div>
  <div class="col-md-5"><b>Domain</b></div>
</div>
<% @configurations.each do |config| %>
  <div class="row">
    <div class="col-md-6">
      <%= config.name %>
    </div>
    <div class="col-md-5">
      <%= config.domain %>
    </div>
    <div class="col-md-1 pull-right">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-cog"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit', edit_configuration_path(config) %></li>
          <li><%= link_to 'Delete', configuration_path(config), method: :delete, data: { confirm: 'Are you sure you want to delete this configuration?' } %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<div>
  <%= link_to 'New Configuration', new_configuration_path, class: 'btn btn-primary' %>
</div>

app/views/configurations/new.html.erb
<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CanvasSeeder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %> <%= params[:action] %>">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Seeder', batches_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Configure', configurations_path %></li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">

  <%= yield %>
  <div class="spacer"/>
</div>
</body>
</html>